### PR TITLE
frzr refactor

### PR DESCRIPTION
**Pull request by NeroReflex**
This is a frzr refactor that has been a work-in-progress for months.

Main points are:
- it supports resuming from hibernation and swap partitions
- it can report progress to an external (graphical) tool so a gui can be developed
- can work with any systemd-based distros
- improved errors handling and debuggability of issues
- allows for multiple kernels being installed in a deployment and create an entry with the right name
- automatically recreate boot entries for old and new deployments
- deployment is more reliable as the switch to a new deployment to boot is only done if no errors occurred
- can easily install kernels that can be used with any installed deployment provided the deployment is compatible with the new frzr (one can still boot and use an old one if initramfs contains all needed drivers)
- the deployment that has deployed the new one will be left bootable even if no errors occurred, but it won't be the default selection (so that in case of problems one can always boot the previous one)
- device-quirks have been separated from frzr as frzr can deal with any distro now
- frzr now supports any initramfs and is not hardcoded to mkinitcpio
- unlock has been made distro-dependent
- technically it can be used to convert any systemd-boot system to a chimeraos system
- it is now possible to develop a tool to restore a deployment to "factory" after that deployment has been unlocked (without downloading anything)
- delta updates can be redistributed
- supports a format that can be streamed directly to btrfs receive and will improve build space on github by a lot
- many more I am sure I just forgot

### CODE REVIEW

**Comment by NeroReflex** [comment]
AUR will need to be fixed too, to know how check this: https://github.com/NeroReflex/chimeraos/tree/master/pkgs/frzr
The 99-frzr-kernel-install.hook will ensure that each time a kernel is installed via pacman bootloader entries are regenerated.

This will make even a better experience than stock archlinux in this regard

**Comment by NeroReflex** [comment]
This refactor is a step forward towards https://github.com/ChimeraOS/frzr/issues/60 
This also fixes https://github.com/ChimeraOS/frzr/issues/22 completely when combined with a systemd-based initramfs
https://github.com/ChimeraOS/frzr/issues/38 this will need to be moved to device-quirks (it's a work-in-progress currently)

**Comment by NeroReflex** [comment]
Just for the record this is fully retro - compatible with older deployments. One can jump between older and newer released. The frzr kernel tool won't really work and device quirks will have to be triggered manually after the update when dowgrading.
If the new image is done correctly an old frzr can jump to a newer-style image.

**Comment by Samsagax** [comment]
I guess you should refactor the tests so they make sense with this new overhaul. The main one is the release image retrieval process.

**Comment by NeroReflex** [comment]
> I guess you should refactor the tests so they make sense with this new overhaul. The main one is the release image retrieval process.

I have never looked into those, maybe @ruineka is more familiar? I saw he started doing tests

**Comment by ruineka** [comment]
> > I guess you should refactor the tests so they make sense with this new overhaul. The main one is the release image retrieval process.
> 
> I have never looked into those, maybe @ruineka is more familiar? I saw he started doing tests

We just need to update the functions to match the new methods and give it dummy information and compare the result. You can take a look into `tests/run.sh`

**Comment by NeroReflex** [comment]
> The main one is the release image retrieval process.

I have set up a test where the current stable is installed on a loopback device that starts as file copy of /dev/zero. If you have other ideas let me know!

**Pull request merged**
