### PR TITLE
Update kernel

### PR DESCRIPTION
**Pull request by Samsagax**
Allow for kernel updates without breaking the install

### CODE REVIEW

**Comment by alkazar** [comment]
How does this prevent breaking the install after kernel updates?
This would require manually running `frzr-deploy --update-bootloader` but it would still not find the newly installed kernel.

**Comment by Samsagax** [comment]
It's true we need to run it manually. We can do a pacman hook for it. It will copy the generated initramfs and kernel image to the deployments boot so it will match the installed modules (the thing preventing from boot).
The bootloader configuration will be reset to our default.

**Comment by alkazar** [comment]
I prefer this solution for the problem of kernel updates:
https://github.com/ChimeraOS/frzr/commit/62934aefc38d350e54cca7585ae8e594377456df

**Comment by Samsagax** [comment]
> I prefer this solution for the problem of kernel updates when unlocked: [62934ae](https://github.com/ChimeraOS/frzr/commit/62934aefc38d350e54cca7585ae8e594377456df)

Seems simpler. Maybe this one could help on argument parsing. If you prefer I'll only keep that part.

**Pull request closed without merging**
